# Site
# repository: nidharaisa/resume
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Raisa Islam
title: Graduate Research Assistant
email: nidha.raisa@gmail.com
phone: 575-805-4181
# website: nidharaisa.github.io/resume

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  nidharaisa
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: nidha-raisa
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0009-0008-8569-1811

# Additional icon links
additional_links:
- title: leetcode
  icon: fas fa-globe
  url: https://leetcode.com/nidha/

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/DP.jpg
about_content: > # | # this will include new lines to allow paragraphs
  Hi, my name is Raisa and currently I'm working as a graduate research assistant at New Mexico Institute of Mining and Technology. I have almost 5 years experience in the software industry. Throughout my working period, I have gained teamwork and leadership skills.
  
content:
  - title: Technical Skills 
    layout: list
    content:
      - layout: left
        title: Proficient
        quote: >
        description: | # this will include new lines to allow paragraphs
          <mark>C/C++</mark> <mark>python</mark> <mark>git</mark> <mark>Network programming</mark> <mark>TCP/IP</mark>
      - layout: left
        title: Exposure
        quote: >
        description: | # this will include new lines to allow paragraphs
          <mark>Java</mark> <mark>JavaScript</mark> <mark>Tomcat</mark> <mark>AWS</mark> <mark>Spring Framework</mark> <mark>SQL</mark> <mark>mySQL</mark> <mark>JNI</mark> <mark>Rest</mark>

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: New Mexico Institute of Mining and Technology
        link: nmt.edu
#         link_text: nmt.edu
        sub_title: Graduate Research Assistant
        caption: August 2019 - Present
        quote: >
        description: | # this will include new lines to allow paragraphs
            - Proposed a comprehensive risk assessment framework using evidential reasoning approach under the Dempster-Shafer theory of belief functions, focusing on fine-grained data analysis.
            - Outlined and implemented ontology based user-centric privacy management system for Smart Grid, empowering the users to personalize their data sharing.
      - layout: left
        title: Reve Systems
        link: revesoft.com
#         link_text: revesoft.com
        sub_title: Software Engineer
        caption: December 2018 - July 2019
        quote: >
        description: | # this will include new lines to allow paragraphs
            - Engineered C++ cross-platform SDK that can support VoIP calls, Instant Messaging features.
            - Implemented JNI wrapper class to integrate SDK into android applications.
            - Developed a cross-platform connection establishment mechanism between web server and mobile apps.
      - layout: left
        title: ringID BD
        link: ringid.com
#         link_text: ringID.com
        sub_title: Software Engineer
        caption: April 2017 - September 2018
        quote: >
        description: |
            - Collaborated as a core member of C++ SDK team, developing SDK for platform engineers to integrate into the social-networking app called ’ringID’ with a user base in the millions.
            - Devised Live Streaming sub-module facilitating real-time audio/video data streaming, featuring capabilities for pausing, resuming, and media-scrubbing.
            - Incorporated various data structures to serve high throughput real time data.
            - Created an Android test app for feature testing prior to their integration into the production codebase
      - layout: left
        title: AnyConnect Pvt Ltd
        link: anyconnect.com
#         link_text: anyconnect.com
        sub_title: Software Engineer
        caption: May 2014 - July 2016
        quote: >
        description: |
            - Designed and implemented a Reliable UDP channel ensuring packet delivery by bandwidth management and re-transmission.
            - Implemented Nested NAT detection mechanism resulting successful P2P connection establishment 90% times.
            - Customized standard ICE check protocol, reducing the data transfer time by 2 to 3 seconds.
            - Integrated unit testing for legacy codebase using Google Test Framework ensuring more than 85% code coverage.
            - Proficiently optimized and sustained legacy C/C++ products.
  
  
  - title: Publications # Title for the section
    layout: text 
    content: | # this will include new lines to allow paragraphs
      List of my publications:
      - [Ontology-based User Privacy Management in the Smart Grid](https://dl.acm.org/doi/10.1145/3477314.3508383)
      - [A Mapping Study on Privacy Attacks in Big Data and IoT](https://ieeexplore.ieee.org/abstract/document/9952824)
      - [Differential privacy applied to smart meters- a mapping study](https://dl.acm.org/doi/10.1145/3412841.3442360)
      - [An Experiment on Feature Selection using Logistic Regression](https://arxiv.org/abs/2402.00201)
  
  
  - title: GitHub Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Face Masking Demo
        link: github.com/nidharaisa/FaceMaskingDemo
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
        description: | # this will include new lines to allow paragraphs
          I started this project to experiment if it is possible to track user face and use mask to communicate with others as anonymous on real-time. This is a <mark>JavaScript</mark> project that used <mark>scaledrone.js</mark> and <mark>tracking.js</mark> library to establish web calls and track face respectively.
      - layout: top-middle
        title: eCash
        link: github.com/nidharaisa/eCash
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
        description: | # this will include new lines to allow paragraphs
          This <mark>C++</mark> project implements an electronic cash system, in which the digital cash cannot be copied and reused more than once and the privacy of the customer’s identity is guaranteed.
  
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-right
        title: New Mexico Institute of Mining and Technology
        sub_title: MS,PhD in Computer Science
        caption: August 2019 - Present
        # quote: >
          # The New Mexico Institute of Mining and Technology (New Mexico Tech or NMT), is a public university in Socorro, New Mexico.
        # description: | # this will include new lines to allow paragraphs
        #  My thesis is focused on user privacy in the smart grid system.

- title: Certifications & Awards # Title for the section
    layout: list 
    content: | # this will include new lines to allow paragraphs
      - [Python for Data Science, AI & Development, Coursera](https://www.coursera.org/account/accomplishments/certificate/HNYUGXUPWC9N)
      - [Data Visualization with Python, Coursera](https://www.coursera.org/account/accomplishments/certificate/24GRG7BQKDNE)
      - Graduate Session 1st Place Poster Award, NMRS 2021
      - People’s Choice Award, NMRS 2021

  - title: Leadership & Memberships # Title for the section
    layout: list 
    content: | # this will include new lines to allow paragraphs
      - President, Association for Computing Machinery - NMT chapter
      - Financial Officer, NMT Bangladeshi Student Association
      - Member: ACM, SWE, NSBE

  - title: A Little More About Me
    layout: list
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Reading
      - Traveling
      - Cooking
#     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

#      Look at this cool image  
#      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
