# Site
repository: nidharaisa/resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Raisa Islam
title: Graduate Research Assistant
email: nidha.raisa@gmail.com
website: nidharaisa.github.io/resume

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  nidharaisa
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: nidha-raisa
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: leetcode
  icon: fas fa-globe
  url: https://leetcode.com/nidha/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Raisa and currently I'm working as a graduate research assistant at New Mexico Institute of Mining and Technology. I have almost 5 years experience in the software industry. Throughout my working period, I have gained teamwork and leadership skills.

  I am most skilled in: <mark>C/C++</mark> <mark>git</mark> <mark>Network protocols</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Reve Systems
        link: https://www.revesoft.com
        # link_text: boringcompany.com
        sub_title: Software Engineer
        caption: December 2018 - July 2019
        quote: >
          # Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            # Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
            - Implemented a cross-platform SDK that can support VoIP calls, IM, etc., features.
            - Implemented JNI wrapper class to integrate SDK into android applications.
            - Developed a cross-platform connection establishment mechanism between web server and several mobile apps.
#       - layout: left
#         title: Ipvision Canada Inc
#         link: http://ipvision.ca/
#         # link_text: boringcompany.com
#         sub_title: Software Engineer
#         caption: April 2017 - September 2018
#         # quote: >
#         #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
#         description: | # this will include new lines to allow paragraphs
#             #Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
#             - Implementation of communication protocols between server and social networking app called RingID.
#             - Designed and implemented Live streaming feature for real-time audio/video data streaming with pause, resume and time-selection options.
#             - Developed android test app for feature testing.
#       - layout: left
#         title: AnyConnect Pvt Ltd
#         link: https://anyconnect.com/
#         # link_text: boringcompany.com
#         sub_title: Software Engineer
#         caption: May 2014 - July 2016
#         # quote: >
#         #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
#         description: | # this will include new lines to allow paragraphs
#             #Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
#             - Designed and implemented a Reliable UDP channel that guarantees packet transmission by bandwidth man- agement and re-transmission.
#             - Implemented Nested NAT detection mechanism that resulted successful P2P connection establishment 90% times.
#             - Implemented TCP send protocol using raw socket.
#             - Optimized ICE check completion time by modifying the standard protocol which improved data transfer time by 2 to 3 seconds.
#             - Unit testing for legacy codebase using Google Test Framework.

  - title: Research Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: New Mexico Institute of Mining and Technology
        link: https://www.nmt.edu/
        # link_text: boringcompany.com
        sub_title: Graduate Research Assistant
        caption: August 2019 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            #Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
            - User-centric privacy management system for Smart Grid that allows the users to classify personal information based on priority level and control sharing of data in order to preserve data privacy. 
            - Privacy based attacks and prevention mechanisms on Big Data and IoT.
#       - layout: left
#         title: Shahjalal University of Science and Technology
#         link: https://www.sust.edu/
#         # link_text: boringcompany.com
#         sub_title: Undergrad Thesis
#         caption: March 2013 - May 2014
#         # quote: >
#         #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
#         description: | # this will include new lines to allow paragraphs
#             #Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
#             - An optical character recognizer (OCR) for Bengali language which can detect some well known Bengali fonts from image files and convert the file into editable text file format.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-right
        title: Institution name
        sub_title: Qualifications (eg. BA Performing Arts)
        caption: Date Range (eg. 2016 - 2019)
        quote: >
          Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          Description of qualification


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
