# Site
repository: nidharaisa/resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Raisa Islam
title: Graduate Research Assistant
email: nidha.raisa@gmail.com
website: nidharaisa.github.io/resume

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  nidharaisa
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: nidha-raisa
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: leetcode
  icon: fas fa-globe
  url: https://leetcode.com/nidha/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Raisa and currently I'm working as a graduate research assistant at New Mexico Institute of Mining and Technology. I have almost 5 years experience in the software industry. Throughout my working period, I have gained teamwork and leadership skills.

  I am most skilled in: <mark>C/C++</mark> <mark>git</mark> <mark>Network programming</mark>

content:
  - title: Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Reve Systems
        link: revesoft.com
#         link_text: revesoft.com
        sub_title: Software Engineer
        caption: December 2018 - July 2019
        quote: >
        description: | # this will include new lines to allow paragraphs
            - Engineered C++ cross-platform SDK that can support VoIP calls, IM, etc., features.
            - Implemented JNI wrapper class to integrate SDK into android applications.
            - Developed a cross-platform connection establishment mechanism between web server and several mobile apps.
      - layout: left
        title: ringID BD
        link: ringid.com
#         link_text: ringID.com
        sub_title: Software Engineer
        caption: April 2017 - September 2018
        quote: >
        description: |
           - Worked as a core member of C++ SDK team, developing SDK for platform engineers to integrate into the social networking app ’ringID’ which is used by millions of users.
           - Designed and implemented Live streaming sub-module responsible for real-time audio/video data streaming that supports pause, resume, time-selection, etc., options.
           - Developed android test app for feature testing testing.
      - layout: left
        title: AnyConnect Pvt Ltd
        link: anyconnect.com
#         link_text: anyconnect.com
        sub_title: Software Engineer
        caption: May 2014 - July 2016
        quote: >
        description: |
            - Designed and implemented a Reliable UDP channel that guarantees packet transmission by bandwidth management and re-transmission.
            - Implemented Nested NAT detection mechanism resulting successful P2P connection establishment 90% times.
            - Optimized ICE check completion time by modifying the standard protocol which improved data transfer time by 2 to 3 seconds.
            - Implemented TCP send protocol using raw socket.
            - Integrated unit testing for legacy codebase using Google Test Framework.

  - title: Research Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: New Mexico Institute of Mining and Technology
        link: nmt.edu
        # link_text: boringcompany.com
        sub_title: Graduate Research Assistant
        caption: August 2019 - Present
        quote: >
        description: | # this will include new lines to allow paragraphs
            User-centric privacy management system for Smart Grid that allows the users to classify personal information based on priority level and control sharing of data in order to preserve data privacy. 
      - layout: left
        title: Shahjalal University of Science and Technology
        link: sust.edu
        # link_text: boringcompany.com
        sub_title: Undergrad Thesis
        caption: March 2013 - May 2014
        quote: >
        description: | # this will include new lines to allow paragraphs
            An optical character recognizer (OCR) for Bengali language which can detect some well known Bengali fonts from image files and convert the file into editable text file format. OCR is developed in <mark>C++</mark> using algorithms like knn, connected component, etc. <mark>Tesseract engine</mark> and <mark>OpenCV</mark> is used for image processing and training dataset.

  - title: GitHub Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Face Masking Demo
        link: github.com/nidharaisa/FaceMaskingDemo
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
        description: | # this will include new lines to allow paragraphs
          I started this project to experiment if it is possible to track user face and use mask to communicate with others as anonymous on real-time. This project is developed in <mark>JavaScript<\mark>, and used <mark>scaledrone.js</mark> and <mark>tracking.js</mark> library to establish web calls and track face respectively.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-right
        title: New Mexico Institute of Mining and Technology
        sub_title: PhD in Computer Science
        caption: August 2021 - May 2025
        quote: >
          Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          Description of qualification


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
